### ISSUE TITLE
Support for async iterators in seq functions

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#1181]
Hi,

Python provides [async for](https://docs.python.org/3/reference/compound_stmts.html#the-async-for-statement) to iterate over async iterators.

The [documentation at the yield special form](https://basilisp.readthedocs.io/en/v0.3.0/specialforms.html#basilisp-specific-special-forms) suggests that "...Basilisp seq and sequence functions integrate seamlessly with Python generators", but it seems that doesn't cover async generators.

For example, given the following python file which defines an `agen` async generator function, and demonstrate its use:
`afor.py`
```python
import asyncio

async def agen():
    for i in range(5):
        await asyncio.sleep(0.01)
        yield i

async def main():
    async for value in agen():
        print(value)

if __name__ == "__main__":
    asyncio.run(main())
```

when run, it successfully iterates over `agen` 
```ps1
> python afor.py
0
1
2
3
4
```

However, If i try to do the same over the same async generator `agen` from Basilisp, using a `seq` (or `vec`), it fails with an `async_generator object is not iterable` error:
`issuefor.lpy`
```clojure
(import asyncio afor)

(defasync main
  []
  (seq (afor/agen)))

(asyncio/run (main))
```
```ps1
> basilisp run issuefor.lpy
Traceback (most recent call last):
...
  File "C:\src\basilisp\src\basilisp\lang\seq.py", line 254, in to_seq
    return _seq_or_nil(sequence(o))
                       ^^^^^^^^^^^
  File "C:\src\basilisp\src\basilisp\lang\seq.py", line 223, in sequence
    i = iter(s)
        ^^^^^^^
TypeError: 'async_generator' object is not iterable

```

I'm not sure what the right solution is here. Would it be possible to extend the "seq and sequence functions" as described in the documentation to support async iterators?

Thanks

**Comment by chrisrink10** [comment]
The problem with Python's async implementation (and why I haven't particularly spent much effort trying to incorporate it into Basilisp) is that functions are "colored" and the specific function color is contagious. Once a function is asynchronous, it can only be used within async contexts (which are the only contexts that can `await` the results). It is likely that the entirety of Basilisp's functional library would require a parallel implementation in order to work in the way you're requesting. 

There are many issues that I see arising, but just to give an example: nearly every Basilisp lazy seq function (e.g. `map`, `filter`, etc.) return a `LazySeq` (as by `lazy-seq`), which is computed by continuously invoking a new function that (typically) returns another `LazySeq` containing an element and yet another function. Just switching the underlying mechanism to an `async def` isn't sufficient because then each call to that function must know to `await` the results rather than simply calling the function. This isn't to mention that the async iterator implementation also contains a completely parallel interface (e.g. `__aiter__` and `__anext__`), which greatly complicates how various components of the ecosystem interact with these new async seqs.

I personally am ok with adding async primitives to Basilisp so users can access them (and fixing issues such as #1179 and #1180), but I do not want to infect the core seq library with Python async (absent a detailed analysis of the effects across the entire project). To me it seems like what you are asking for should instead be a separate `contrib` style library in Clojure with variants of `alazy-seq`, `amap`, `afilter`, etc.

**Comment by ikappaki** [comment]
> The problem with Python's async implementation (and why I haven't particularly spent much effort trying to incorporate it into Basilisp) is that functions are "colored" and the specific function color is contagious. Once a function is asynchronous, it can only be used within async contexts (which are the only contexts that can `await` the results). It is likely that the entirety of Basilisp's functional library would require a parallel implementation in order to work in the way you're requesting.
> 
> There are many issues that I see arising, but just to give an example: nearly every Basilisp lazy seq function (e.g. `map`, `filter`, etc.) return a `LazySeq` (as by `lazy-seq`), which is computed by continuously invoking a new function that (typically) returns another `LazySeq` containing an element and yet another function. Just switching the underlying mechanism to an `async def` isn't sufficient because then each call to that function must know to `await` the results rather than simply calling the function. This isn't to mention that the async iterator implementation also contains a completely parallel interface (e.g. `__aiter__` and `__anext__`), which greatly complicates how various components of the ecosystem interact with these new async seqs.
>
> I personally am ok with adding async primitives to Basilisp so users can access them (and fixing issues such as #1179 and #1180), but I do not want to infect the core seq library with Python async (absent a detailed analysis of the effects across the entire project). To me it seems like what you are asking for should instead be a separate `contrib` style library in Clojure with variants of `alazy-seq`, `amap`, `afilter`, etc.

Right, thanks for taking the time to explain the situation and highlighting the challenges with async constructs in python. My knowledge of this subject is fairly superficial, but I wanted to bring attention to it as a potential gap. This particular issue caught my attention after reviewing `async with`.

Creating an external library to address this seems like an excellent idea, provided, as you mentioned, that the necessary primitives are in place. Do you have any initial thoughts on how an `async for` concept could be supported as a primitive construct? The first approach that comes to mind is something like `^:async for`, but I'm not sure what challenges that might involve.

**Comment by chrisrink10** [comment]
> Creating an external library to address this seems like an excellent idea, provided, as you mentioned, that the necessary primitives are in place. Do you have any initial thoughts on how an `async for` concept could be supported as a primitive construct? The first approach that comes to mind is something like `^:async for`, but I'm not sure what challenges that might involve.

I may be misunderstanding you but I don't think Clojure/Basilisp `for` is what I would consider a primitive (from the perspective of a Python async). I would not support creating or supporting asynchronous operations directly using the Basilisp `for` construct. By primitives, I mean the building blocks of asynchronous functions (being able to define async functions and await their results). The library would be responsible for creating its own interfaces and operating on them.

If you're just talking about how to adapt a Python `async for` into Basilisp, you'd need to probably create a parallel interface to `ISeq` (like `IAsyncSeq`) which has async variants of all of the `ISeq` methods and dunders. Then presumably you'd just coerce any asynchronous generator or sequence into a sequence using something like an `aseq` function which could then be passed to any other asynchronous seq function.

**Comment by ikappaki** [comment]
> > Creating an external library to address this seems like an excellent idea, provided, as you mentioned, that the necessary primitives are in place. Do you have any initial thoughts on how an `async for` concept could be supported as a primitive construct? The first approach that comes to mind is something like `^:async for`, but I'm not sure what challenges that might involve.
> 
> I may be misunderstanding you but I don't think Clojure/Basilisp `for` is what I would consider a primitive (from the perspective of a Python async). I would not support creating or supporting asynchronous operations directly using the Basilisp `for` construct. By primitives, I mean the building blocks of asynchronous functions (being able to define async functions and await their results). The library would be responsible for creating its own interfaces and operating on them.
> 
> If you're just talking about how to adapt a Python `async for` into Basilisp, you'd need to probably create a parallel interface to `ISeq` (like `IAsyncSeq`) which has async variants of all of the `ISeq` methods and dunders. Then presumably you'd just coerce any asynchronous generator or sequence into a sequence using something like an `aseq` function which could then be passed to any other asynchronous seq function.

My reasoning was as follows: Python has a primitive `async for` construct (backed by [ast.AsynFor](https://docs.python.org/3/library/ast.html#ast.AsyncFor)), so I though it reasonable to suggest a Basilisp "primitive" function counterpart. A direct translation to to the python AST would likely be the most perforrmant.  Since this involves a python `for` function, the idea of supporting an `^:async` metadata tag in Basilisp `for` initially seemed like an nice syntactic suggestion.

I hope this clarifies a bit my train of thought behind to the suggestion.

To summarize the options discussed

1. Create a parallel interface to `ISeq` (like `IAsyncSeq`) which has async variants of all the `ISeq` methods and dunders. 
2. Support a Basilisp construct that directly translates to an `AsyncFor` AST node. Examples options include a new primitive like `python/asyncfor` , or an`^:async for` (which you have rightly discounted), or  or any other better syntactic construct t to generate an  `AsyncFor` AST node.

Does option 2 seem feasible and something that you might consider? Option 1 feels like overkill to me and seems to me.

here’s an example of how I imagine `python/asyncfor` could look like building on the original example of this ticket:
```clojure
(import asyncio afor)

(defasync main
  []
  (python/asyncfor [value (afor/agen)]
                   (println value)))

(asyncio/run (main))
```

Thanks

**Comment by amano-kenji** [comment]
* Does clojure's `core.async` help with this?
* What about creating a seq of async functions that you can await in an async function?

**Comment by amano-kenji** [comment]
It turns out that lazy-seq is not compatible with asyncio.

**Comment by amano-kenji** [comment]
I want basilisp to be able to work with asynchronous code well. Basilisp should be able to do things like async for and async with.

I'm new to basilisp, so I don't really know much. Can someone publish a contrib library that can  experiment with async API?

**Comment by amano-kenji** [comment]
* `(seq (afor/agen))` seems wrong because the documentation for `asyncio/run` doesn't way `asyncio/run` returns a value.
* basilisp can have primitives that compile to AST expressions for `async for` and `async with`, or there can be macros or functions that mimic `async for` and `async with` as below.

```
iter = (ITER)
iter = type(iter).__aiter__(iter)
running = True

while running:
    try:
        TARGET = await type(iter).__anext__(iter)
    except StopAsyncIteration:
        running = False
    else:
        SUITE
else:
    SUITE2
```
```
manager = (EXPRESSION)
aenter = type(manager).__aenter__
aexit = type(manager).__aexit__
value = await aenter(manager)
hit_except = False

try:
    TARGET = value
    SUITE
except:
    hit_except = True
    if not await aexit(manager, *sys.exc_info()):
        raise
finally:
    if not hit_except:
        await aexit(manager, None, None, None)
```

* Someone can publish a library that implements aseq, lazy-aseq, amap, afilter, and so on.

**Comment by amano-kenji** [comment]
While I think `async-with` is beneficial, I have substitutes for `async-for`.

Things like `areduce`, `atransduce`, and `acomp` can, in theory, build up a transient data structure until an async iterator is consumed and return a persistent data structure.

**Comment by amano-kenji** [comment]
I think there could be a basilisp library that has transformation functions for async iterators.

* `(basilisp.async-iter/map f async-iter)` returns a mapped async-iter.
* `(basilisp.async-iter/reduce f (val) async-iter)` returns a coroutine that returns a reduced value.
* `(basilisp.async-iter/filter pred async-iter)` returns a coroutine that returns a filtered async-iter.
* `(basilisp.async-iter/transduce xform f  (init) async-iter)` returns a coroutine that returns a transduced value
* `(basilisp.async-iter/into to xform async-iter)`
* `(basilisp.async-iter/doall n async-iter)`?
* `(basilisp.async-iter/dorun n async-iter)`?
* ...

**Comment by amano-kenji** [comment]
If `core.async` is implemented, then we can work with channels instead of the above interfaces.

**Comment by amano-kenji** [comment]
python 3.13 has experimental support for free threading which disables GIL for multi-thread performance.

With or without free threading, asyncio can run on a separate thread where asyncio sends async iterator items to another thread via a thread-safe queue. You can write QueueIterator class to turn an async iterator to an iterator which you can turn into a seq. QueueIterator class creates a thread-safe queue and a new thread that feeds async iterator items to the queue. The class also joins the thread after the async iterator produces the last item.

This QueueIterator trick adds an overhead with queue and thread, but I guess you can even implement core.async with this.

**Comment by amano-kenji** [comment]
This example code snippet works perfectly with python 3.12.

```python
import asyncio
import threading
import queue

async def agen():
    for i in range(5):
        await asyncio.sleep(0.01)
        yield i

def run_async_iterator_in_thread(async_iterable, output_queue):
    async def async_runner():
        async for item in async_iterable:
            output_queue.put(item)
        output_queue.put(None)

    asyncio.run(async_runner())

class QueueIterator:
    def __init__(self, async_iterable):
        self.queue = queue.Queue()
        self.thread = threading.Thread(
            target=run_async_iterator_in_thread,
            args=(async_iterable, self.queue)
        )
        self.thread.start()

    def __iter__(self):
        return self

    def __next__(self):
        item = self.queue.get()
        if item is None:
            self.thread.join()
            raise StopIteration
        return item

if __name__ == "__main__":
    for item in QueueIterator(agen()):
        print(item)
```

**Comment by amano-kenji** [comment]
I didn't realize that we don't know what ikappaki wants to do. What do you really want to do?

Depending on what you want, just implementing `async-for` and async generator can be enough.

**Comment by amano-kenji** [comment]
I think we should design an idiomatic API for async-for and async generator from lower constructs.

For example, an async generator can be expressed as an async iterator which is a class instance. An idiomatic API can build on top of an async iterator and expose a function for creating an async iterator.

A generator can also be expressed as an iterator. An idiomatic API can exist for creating one and abstracting over it.

**Comment by amano-kenji** [comment]
I'm starting to think that you should use something like gevent or promesa's [core.async](https://funcool.github.io/promesa/latest/channels.html) instead of asyncio. Promesa hands over blocking I/O operations to a dynamically growing thread pool on JVM and returns promises.

Gevent spares you from asyncio by monkey-patching blocking I/O operations and running them in its own green threads.

**Comment by amano-kenji** [comment]
I think core.async is better than having python async constructs. https://github.com/basilisp-lang/basilisp/issues/149 for details.

**Comment by chrisrink10** [comment]
> Since this involves a python for function, the idea of supporting an `^:async` metadata tag in Basilisp `for` initially seemed like an nice syntactic suggestion.

Basilisp `for` is not equivalent to Python `for` though. Basilisp `for` is the Clojure variant, which is much more complex and sophisticated than the Python construct.

I think this functionality is something that can be created with a macro. Python's own documentation says that

```python
async for TARGET in ITER:
    SUITE
else:
    SUITE2
```

is semantically equivalent to:

```python
iter = (ITER)
iter = type(iter).__aiter__(iter)
running = True

while running:
    try:
        TARGET = await type(iter).__anext__(iter)
    except StopAsyncIteration:
        running = False
    else:
        SUITE
else:
    SUITE2
```

I think you could probably create this with a macro using existing constructs.

**Comment by chrisrink10** [comment]
@ikappaki I put up #1226 with a possible macro solution. Let me know if that might work for you. I will try to write tests in the next few days.
