### ISSUE TITLE
`deftype` and `defrecord` constructors don't support `.` suffix

### ISSUE THREAD

**Issue by chrisrink10** [basilisp-lang/basilisp#383]
Given a `defrecord` or `deftype` form, attempting to call its constructor as you might other forms fails in curious ways:

```clojure
(defrecord Circle [radius])
```

 * Qualified with no namespace (works in Clojure):

```
user=> (user.Circle. 1)
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 159, in repl
    result = eval_str(lsrc, ctx, ns.module, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 75, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, module)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 107, in compile_and_exec_form
    lisp_ast = parse_ast(ctx.parser_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2433, in parse_ast
    return _parse_ast(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1609, in _invoke_ast
    fn = _parse_ast(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2388, in _parse_ast
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2202, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2180, in _resolve_sym
    return __resolve_namespaced_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2128, in __resolve_namespaced_symbol
    f"unable to resolve symbol '{form}' in this context", form=form
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'user/Circle' in this context
```

 * Unqualified, same namespace (works in Clojure):

```
user=> (Circle. 1)
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 159, in repl
    result = eval_str(lsrc, ctx, ns.module, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 75, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, module)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 107, in compile_and_exec_form
    lisp_ast = parse_ast(ctx.parser_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2433, in parse_ast
    return _parse_ast(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1609, in _invoke_ast
    fn = _parse_ast(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2388, in _parse_ast
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2202, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2182, in _resolve_sym
    return __resolve_bare_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2158, in __resolve_bare_symbol
    assert munged not in vars(ctx.current_ns.module)
AssertionError
```

 * Using `new` with qualified, no-namespace name (works in Clojure):

```
user=> (new user.Circle 1)
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1616, in _invoke_ast
    expanded_ast = _parse_ast(ctx, expanded)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 484, in _parse_form
    return f(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1609, in _invoke_ast
    fn = _parse_ast(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 484, in _parse_form
    return f(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2388, in _parse_ast
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2202, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2180, in _resolve_sym
    return __resolve_namespaced_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2128, in __resolve_namespaced_symbol
    f"unable to resolve symbol '{form}' in this context", form=form
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'user/Circle' in this context

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 159, in repl
    result = eval_str(lsrc, ctx, ns.module, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 75, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, module)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 107, in compile_and_exec_form
    lisp_ast = parse_ast(ctx.parser_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2433, in parse_ast
    return _parse_ast(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1631, in _invoke_ast
    ) from e
basilisp.lang.compiler.exception.CompilerException: error occurred during macroexpansion
```

* Using `new` with bare name in same namespace (works in Clojure):

```
user=> (new Circle 1)
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1616, in _invoke_ast
    expanded_ast = _parse_ast(ctx, expanded)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 484, in _parse_form
    return f(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1609, in _invoke_ast
    fn = _parse_ast(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 484, in _parse_form
    return f(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2388, in _parse_ast
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2202, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2182, in _resolve_sym
    return __resolve_bare_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2158, in __resolve_bare_symbol
    assert munged not in vars(ctx.current_ns.module)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 159, in repl
    result = eval_str(lsrc, ctx, ns.module, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 75, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, module)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 107, in compile_and_exec_form
    lisp_ast = parse_ast(ctx.parser_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2433, in parse_ast
    return _parse_ast(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1631, in _invoke_ast
    ) from e
basilisp.lang.compiler.exception.CompilerException: error occurred during macroexpansion
```

 * Qualified with namespace (also fails in Clojure):

```
user=> (user/Circle 1)
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 159, in repl
    result = eval_str(lsrc, ctx, ns.module, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 75, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, module)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 107, in compile_and_exec_form
    lisp_ast = parse_ast(ctx.parser_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2433, in parse_ast
    return _parse_ast(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2374, in _parse_ast
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2038, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 1609, in _invoke_ast
    fn = _parse_ast(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 486, in _parse_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2388, in _parse_ast
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2202, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2180, in _resolve_sym
    return __resolve_namespaced_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/parser.py", line 2128, in __resolve_namespaced_symbol
    f"unable to resolve symbol '{form}' in this context", form=form
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'user/Circle' in this context
```

**Comment by chrisrink10** [comment]
Turns out this issue had been fixed at some point but I added some tests in #629 to ensure we don't have a regression.
