### ISSUE TITLE
References to Vars in Namespaces whose aliase matches imported Python modules fail

### ISSUE THREAD

**Issue by chrisrink10** [basilisp-lang/basilisp#483]
Suppose you have a namespace `basilisp.json` (which imports Pythons `json` module). If you were to `(require '[basilisp.json :as json])` and attempt to call a function from that Namespace, you would get a Compiler error ("can't identify aliased form"). A full example is given below:

```
basilisp.user=> (require '[basilisp.json :as json])
nil

basilisp.user=> (json/write-str #{:a :b :c})
Traceback (most recent call last):
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 138, in repl
    result = eval_str(lsrc, ctx, ns, eof)
  File "/Users/christopher/Projects/basilisp/src/basilisp/cli.py", line 51, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, ns)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/__init__.py", line 111, in compile_and_exec_form
    lisp_ast = analyze_form(ctx.analyzer_context, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2893, in analyze_form
    return _analyze_form(ctx, form).assoc(top_level=True)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 597, in _analyze_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2834, in _analyze_form
    return _list_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2351, in _list_node
    return _invoke_ast(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 1770, in _invoke_ast
    fn = _analyze_form(ctx, form.first)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 597, in _analyze_form
    return f(ctx, form).fix_missing_locations(form_loc)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2848, in _analyze_form
    return _symbol_node(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2655, in _symbol_node
    return _resolve_sym(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2633, in _resolve_sym
    return __resolve_namespaced_symbol(ctx, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2544, in __resolve_namespaced_symbol
    resolved = __resolve_namespaced_symbol_in_ns(ctx, current_ns, form)
  File "/Users/christopher/Projects/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2468, in __resolve_namespaced_symbol_in_ns
    raise AnalyzerException("can't identify aliased form", form=form)
basilisp.lang.compiler.exception.CompilerException: can't identify aliased form
```

The solution can be resolved with this change to `basilisp.lang.compiler.analyzer`:

```diff
@@ -2442,6 +2442,10 @@ def __resolve_namespaced_symbol_in_ns(  # pylint: disable=too-many-branches
             ns = which_ns.import_aliases[ns_sym]
             assert ns is not None
             ns_name = ns.name
+        elif ns_sym in which_ns.aliases:
+            ns = which_ns.aliases[ns_sym]
+            assert ns is not None
+            ns_name = ns.name
         else:
             ns_name = ns_sym.name
``

**Comment by chrisrink10** [comment]
The solution described above is not the correct solution for this problem. It turns out this ended up being caused by some of the changes in #481 

The `basilisp.lang.compiler.generator` still `import`s Python modules as soon as it generates the code. Unfortunately, this ends up happening often times before an `in-ns` call has happened (and consequently that the compiler has registered a changed `*ns*` value.
