### ISSUE TITLE
Unable to setup namespace with `ns` after its creation using `in-ns`

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#718]
using `ns` to setup a namespace using `in-ns` on the REPL fails:
```
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'ns' in this context
```

To reproduce
1. open up the REPL
2. call `in-ns` to create a namespace and try to set it up with `ns`, an exception is raised
``` clojure
basilisp.user=> (in-ns 'xyz)
xyz

xyz=> (ns xyz)
Traceback (most recent call last):
  File "C:\src\basilisp\src\basilisp\cli.py", line 306, in repl
    result = eval_str(lsrc, ctx, ns, eof)
  File "C:\src\basilisp\src\basilisp\cli.py", line 52, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, ns)
  File "C:\src\basilisp\src\basilisp\lang\compiler\__init__.py", line 142, in compile_and_exec_form
    lisp_ast = analyze_form(ctx.analyzer_context, form)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 3704, in analyze_form
    return _analyze_form(form, ctx).assoc(top_level=True)
  File "D:\local\Python38\lib\functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 676, in _analyze_form
    return f(form, ctx).fix_missing_locations(form_loc)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 3137, in _list_node
    return _invoke_ast(form, ctx)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 2403, in _invoke_ast
    fn = _analyze_form(form.first, ctx)
  File "D:\local\Python38\lib\functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 676, in _analyze_form
    return f(form, ctx).fix_missing_locations(form_loc)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 3439, in _symbol_node
    return _resolve_sym(ctx, form)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 3417, in _resolve_sym
    return __resolve_bare_symbol(ctx, form)
  File "C:\src\basilisp\src\basilisp\lang\compiler\analyzer.py", line 3390, in __resolve_bare_symbol
    raise AnalyzerException(
basilisp.lang.compiler.exception.CompilerException: unable to resolve symbol 'ns' in this context {:form ns :phase :analyzing}
```

The same works on the clojure REPL
``` clojure
Clojure 1.11.1
user=> (in-ns 'xyz)
#object[clojure.lang.Namespace 0x4837595f "xyz"]
xyz=> (ns xyz)
nil
xyz=> *ns*
#object[clojure.lang.Namespace 0x4837595f "xyz"]
xyz=> 
```

**Comment by chrisrink10** [comment]
Fixed in #727
