### ISSUE TITLE
`intern` throws exception when used

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#724]
Hi,

`basilisp.core/intern` throws an error when used:
```
AttributeError: 'Var' object has no attribute 'set_root'
```

To reproduce
1. Open the REPL, and try to intern a symbol:
``` clojure
basilisp.user=> (intern 'basilisp/user 'x "Foobar")
Traceback (most recent call last):
  File "C:\src\basilisp\src\basilisp\cli.py", line 306, in repl
    result = eval_str(lsrc, ctx, ns, eof)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\basilisp\src\basilisp\cli.py", line 52, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, ns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\basilisp\src\basilisp\lang\compiler\__init__.py", line 165, in compile_and_exec_form
    return getattr(ns.module, final_wrapped_name)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REPL Input>", line 1, in __lisp_expr___5878
  File "C:\src\basilisp\src\basilisp\core.lpy", line 4531, in intern
    (defn intern
  File "C:\src\basilisp\src\basilisp\core.lpy", line 4542, in intern__arity3
    (.intern ns v))))
AttributeError: 'Var' object has no attribute 'set_root'
```

Patch to follow.

**Comment by chrisrink10** [comment]
Fixed in #725
