### ISSUE TITLE
defrecord fails when record name contains a hyphen

### ISSUE THREAD

**Issue by ikappaki** [basilisp-lang/basilisp#777]
`defrecord` fails when there is a hyphen in its name
` assert munged not in vars(current_ns.module) `

to reproduce
1. open up the REPL and create a record with a hyphen in its name
``` Clojure
basilisp.user=> (defrecord abc-a [a b c])
<class 'basilisp.user.abc_a'>
```
2. Try to create a record instance
``` clojure
basilisp.user=> (abc-a. 1 2 3)
Traceback (most recent call last):
  File "/src/basilisp/src/basilisp/cli.py", line 353, in repl
    result = eval_str(lsrc, ctx, ns, eof)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/cli.py", line 44, in eval_str
    last = compiler.compile_and_exec_form(form, ctx, ns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/__init__.py", line 164, in compile_and_exec_form
    lisp_ast = analyze_form(ctx.analyzer_context, form)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 3735, in analyze_form
    return _analyze_form(form, ctx).assoc(top_level=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 680, in _analyze_form
    return f(form, ctx).fix_missing_locations(form_loc)
           ^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 3165, in _list_node
    return _invoke_ast(form, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 2430, in _invoke_ast
    fn = _analyze_form(form.first, ctx)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 680, in _analyze_form
    return f(form, ctx).fix_missing_locations(form_loc)
           ^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 3467, in _symbol_node
    return _resolve_sym(ctx, form)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 3445, in _resolve_sym
    return __resolve_bare_symbol(ctx, form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/basilisp/src/basilisp/lang/compiler/analyzer.py", line 3417, in __resolve_bare_symbol
    assert munged not in vars(current_ns.module)
```

Not sure how to fix this.

Thanks

**Comment by chrisrink10** [comment]
I have identified the problem and will put up a PR shortly.
